### ISSUE TITLE
suggestions pass 1

### ISSUE THREAD

**Issue by killua-eu** [Industra/manual-nova63#1]
suggestions:

- **quick checklist** add item 'frame before starting job' (security precaution)
- deduplicate content of **notes** and **security and physical manipulation**
- rename **Security and Physical manipulation** to **Operation and safety**
- add to do's / dont's: moving the gantry and the up/down table with loading door opened
- add subchapters:
  - Hazards and risks
    - fire (ignition of processed material)
    - laser beam irradiation (loss of eyesight, severe burn injuries) from direct and reflected beam
    - mechanical damage or injury 
       - fingers / hair / clothes can get pulled or crushed (movement of head/table with loading door opened)
       - laser head and other parts of the machine can get damaged (curved/non-planar materials)
  - Safety features and protective equipment
     - Central stop
     - Fire extinguisher
     - Certified laser protecting goggles
  - Operational accident / malfunction procedures
     - Job doesn't start
     - Job didn't finish
     - Fire
  - First aid: Please refer to general safety instructions, esp. chapters on
  burns, inhalation of toxic fumes, laser beam irradiation and, mechanical injury.

**Comment by berkas1** [comment]
- frame before starting job -> there is no security risk in not doing that, it just shows wrong point of origin etc...
- duplicity OK
- renaming OK
- sub chapters added
- first aid added

**Comment by killua-eu** [comment]
- Include example to forbidden Materials, 
    - bullet point 1 - i.e. add: (i.e. PVC, vinyl, artificial leather)
 - `Hazards and Risks`, bullet point 2, missing closing )
 - Add "toxic and/or corrosive fumes" to `Hazards and Risks`
 - Consider 
   - Renaming `Hazards and Risks` to `Operational Hazards and Risks`
   - Renaming `Operational Accidents / Malfunction Procedures` to `Operational Malfunction`
   - dropping "fire" from `Operational Malfunction`

**Comment by killua-eu** [comment]
pull in info from https://wiki.oulu.fi/pages/viewpage.action?pageId=69796385 to our wiki and the guide?

**Comment by berkas1** [comment]
agreed, new version: https://github.com/Industra/manual-nova63/releases/latest/download/manual.pdf

**Comment by berkas1** [comment]
Closing this for now, it seems to be ok for first release. Let's continue in a new 'pass 2' issue if necessary.
